version: '3.9'

services:
  postgres:
    container_name: graphqldb
    image: postgres:latest
    restart: always
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - data_db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pg_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
     - postgres
volumes:
 data_db: {}
 pg_data: {}